apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "langstream.clientFullname" . }}
  labels:
    {{- include "langstream.clientLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.client.replicaCount }}
  selector:
    matchLabels:
      {{- include "langstream.clientSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.client.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "langstream.clientSelectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.client.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.client.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.client.securityContext | nindent 12 }}
          image: "{{ .Values.client.image.repository }}:{{ .Values.client.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.client.image.pullPolicy }}
          resources:
            {{- toYaml .Values.client.resources | nindent 12 }}
          command: [ "sh", "-c" ]
          args:
            - > 
                echo "webServiceUrl: $WEB_SERVICE_URL" > /app/conf/cli.yaml &&
                echo "apiGatewayUrl: $API_GATEWAY_URL" >> /app/conf/cli.yaml &&
                echo "tenant: $TENANT" >> /app/conf/cli.yaml &&                
                env &
                sleep infinity
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - configMapRef:
                name: {{ include "langstream.clientFullname" . }}
      {{- with .Values.client.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.client.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.client.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
