apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "langstream.apiGatewayFullname" . }}
  labels:
    {{- include "langstream.apiGatewayLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.apiGateway.replicaCount }}
  selector:
    matchLabels:
      {{- include "langstream.apiGatewaySelectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.apiGateway.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "langstream.apiGatewaySelectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.apiGateway.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "langstream.apiGatewayServiceAccountName" . }}
      securityContext:
        {{- toYaml .Values.apiGateway.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.apiGateway.securityContext | nindent 12 }}
          image: "{{ .Values.apiGateway.image.repository }}:{{ .Values.apiGateway.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.apiGateway.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.apiGateway.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /management/health
              port: http
          readinessProbe:
            httpGet:
              path: /management/health
              port: http
          resources:
            {{- toYaml .Values.apiGateway.resources | nindent 12 }}
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - configMapRef:
                name: {{ include "langstream.apiGatewayFullname" . }}
      {{- with .Values.apiGateway.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apiGateway.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apiGateway.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
